spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeffzaza/spring-boot-tutor-config
          searchPaths: lab-8
server:
  port: 8001
management:
  security:
    enabled: false